class MeasureType:
        ONBEKEND = 0
        ALGEMENE_MAATREGEL = 1
        ONGEDEFINIEERD = 255

class SubMeasureType:
	EXTRA_VERVOER = '0'
	VERVALLEN_HALTE = '1'
	VERVANGENDE_HALTE = '2'
	RIJDEN_VIA_OMWEG = '3'
	GEEN_BUSINZET = '4__1'
	BEPERKTE_BUSINZET = '4__2'
	BUSINZET = '4__3'
	GEEN_TREINEN = '5__1'
	MINDER_TREINEN = '5__2'
	TREINEN_RIJDEN_VIA = '5__3'
	GEEN = '6'
	ROUTE_AANGEPAST = '7'
